

using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using SmartLifeSolution.DAL.Models;

namespace SmartLifeSolution.DAL.DBContexts
{
    public class ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : IdentityDbContext<ApplicationUser>(options)
    {
        public DbSet<ApplicationUser> ApplicationUser { get; set; }
        public DbSet<ApplicationRole> ApplicationRole { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Gateway> Gateways { get; set; }
        public DbSet<GatewayDevice> GatewayDevices { get; set; }
        public DbSet<GatewayDeviceData> GatewayDeviceData { get; set; }    
        public DbSet<DeviceTypes> DeviceType { get; set; } 
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<UserRoleMenu> UserRoleMenus { get; set; }
        public DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }
        public DbSet<UserSubscription> UserSubscriptions { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<WidgetType> WidgetTypes { get; set; }
        public DbSet<WidgetCategory> WidgetCategories { get; set; }
        public DbSet<UserWidget> UserWidgets { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<TemplateWidget> TemplateWidgets { get; set; }
        public DbSet<UserDashboard> UserDashboards { get; set; }
        public DbSet<UserDashboardWidget> UserDashboardWidgets { get; set; }


        //public DbSet<SmartBuilding> SmartBuildings { get; set; }
        //public DbSet<Floor> Floors { get; set; }
        //public DbSet<Room> Rooms { get; set; }
        // public DbSet<Appliance> Appliances { get; set; }

        // protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        // {

        ////     optionsBuilder
        ////.UseSqlServer(
        ////    @"Server=localhost;Database=SmartLife;Integrated Security=True;Encrypt=Optional;",
        ////    options => options.EnableRetryOnFailure());

        //     optionsBuilder.UseSqlServer("Server=localhost;Database=SmartLife;Integrated Security=True;Encrypt=Optional;", builder =>
        //     {
        //         builder.EnableRetryOnFailure(5, TimeSpan.FromSeconds(10), null);
        //     });
        //     base.OnConfiguring(optionsBuilder);

        // }

        // Optionally, configure additional entity settings (like GUID as PK)
        //protected override void OnModelCreating(ModelBuilder modelBuilder)
        //{
        //    //modelBuilder.Entity<Device>()
        //    //    .Property(p => p.Id)
        //    //    .HasDefaultValueSql("NEWID()");  // Ensures GUID is generated by SQL Server
        //}
    }
}
